// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","parentId":"@@/global-layout","id":"1"},"2":{"path":"/login","parentId":"@@/global-layout","id":"2"},"3":{"path":"/login/register","parentId":"@@/global-layout","id":"3"},"4":{"path":"/login/forget","parentId":"@@/global-layout","id":"4"},"5":{"path":"/login/review","parentId":"@@/global-layout","id":"5"},"6":{"path":"/scan","parentId":"@@/global-layout","id":"6"},"7":{"path":"/scanCheck","parentId":"@@/global-layout","id":"7"},"8":{"path":"/verify","parentId":"@@/global-layout","id":"8"},"9":{"path":"/personal","parentId":"@@/global-layout","id":"9"},"10":{"path":"/personal/qrcode","parentId":"@@/global-layout","id":"10"},"11":{"path":"/*","parentId":"@@/global-layout","id":"11"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__login__index__index" */'@/pages/login/index/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__login__register__index" */'@/pages/login/register/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__login__forget__index" */'@/pages/login/forget/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__login__review__index" */'@/pages/login/review/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__scan__index" */'@/pages/scan/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__scanCheck__index" */'@/pages/scanCheck/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__verify__index" */'@/pages/verify/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__personal__index" */'@/pages/personal/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__qrcode__index" */'@/pages/qrcode/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/weitaoren/Documents/workspace/guangpeng/tx-frontend/src/layouts/index.tsx')),
},
  };
}
