// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"path":"*","id":"404","parentId":"@@/global-layout"},"login/register/index":{"path":"login/register","id":"login/register/index","parentId":"@@/global-layout"},"login/forget/index":{"path":"login/forget","id":"login/forget/index","parentId":"@@/global-layout"},"login/review/index":{"path":"login/review","id":"login/review/index","parentId":"@@/global-layout"},"login/index/index":{"path":"login","id":"login/index/index","parentId":"@@/global-layout"},"scanCheck/index":{"path":"scanCheck","id":"scanCheck/index","parentId":"@@/global-layout"},"personal/index":{"path":"personal","id":"personal/index","parentId":"@@/global-layout"},"qrcode/index":{"path":"qrcode","id":"qrcode/index","parentId":"@@/global-layout"},"verify/index":{"path":"verify","id":"verify/index","parentId":"@@/global-layout"},"scan/index":{"path":"scan","id":"scan/index","parentId":"@@/global-layout"},"index":{"path":"/","id":"index","parentId":"@@/global-layout"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "src__pages__404" */'../../../src/pages/404.tsx')),
'login/register/index': React.lazy(() => import(/* webpackChunkName: "src__pages__login__register__index" */'../../../src/pages/login/register/index.tsx')),
'login/forget/index': React.lazy(() => import(/* webpackChunkName: "src__pages__login__forget__index" */'../../../src/pages/login/forget/index.tsx')),
'login/review/index': React.lazy(() => import(/* webpackChunkName: "src__pages__login__review__index" */'../../../src/pages/login/review/index.tsx')),
'login/index/index': React.lazy(() => import(/* webpackChunkName: "src__pages__login__index__index" */'../../../src/pages/login/index/index.tsx')),
'scanCheck/index': React.lazy(() => import(/* webpackChunkName: "src__pages__scanCheck__index" */'../../../src/pages/scanCheck/index.tsx')),
'personal/index': React.lazy(() => import(/* webpackChunkName: "src__pages__personal__index" */'../../../src/pages/personal/index.tsx')),
'qrcode/index': React.lazy(() => import(/* webpackChunkName: "src__pages__qrcode__index" */'../../../src/pages/qrcode/index.tsx')),
'verify/index': React.lazy(() => import(/* webpackChunkName: "src__pages__verify__index" */'../../../src/pages/verify/index.tsx')),
'scan/index': React.lazy(() => import(/* webpackChunkName: "src__pages__scan__index" */'../../../src/pages/scan/index.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "src__pages__index" */'../../../src/pages/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/weitaoren/Documents/workspace/guangpeng/tx-frontend/src/layouts/index.tsx')),
},
  };
}
